baseURL: "lijianxiong.art" 
title: Jianxiong Li
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Blog
          url: blog/
          weight: 5 
        - name: Arxiv
          url: arxiv/
          weight: 2
        

params:
    description: "."
    author: Jianxiong Li
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jianxiong Li
          subtitle: "Hi! I am a master’s student at Guangzhou University, supervised by Professor Zhigang Wang. I received my bachelor’s degree in Intelligent Science and Technology from Sun Yat-sen University."
          imageUrl: "1751468479701.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Blog
              url: blog/
            - name: Arxiv
              url: arxiv/

    socialIcons:
        - name: Email
          url: mailto:li.jian.xiong@qq.com
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/
        - name: GitHub
          url: https://github.com/
        - name: Twitter
          url: https://x.com/



    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jianxiong Li"
      icon: fluid.png
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
